export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILED = "FETCH_RECIPES_FAILED";

export const RATE_RECIPE = "RATE_RECIPE";
export const RATE_RECIPE_SUCCESS = "RATE_RECIPE_SUCCESS";
export const RATE_RECIPE_FAILED = "RATE_RECIPE_FAILED";

export const TOGGLE_FAVORITE_RECIPE = "TOGGLE_FAVORITE_RECIPE";
export const TOGGLE_FAVORITE_RECIPE_SUCCESS = "TOGGLE_FAVORITE_RECIPE_SUCCESS";
export const TOGGLE_FAVORITE_RECIPE_FAILED = "TOGGLE_FAVORITE_RECIPE_FAILED";
